# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DM3Viewer.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DM3Viewer(object):
    def setupUi(self, DM3Viewer):
        DM3Viewer.setObjectName(_fromUtf8("DM3Viewer"))
        DM3Viewer.resize(827, 746)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DM3Viewer.sizePolicy().hasHeightForWidth())
        DM3Viewer.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/viewer.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DM3Viewer.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(DM3Viewer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.plotQF = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotQF.sizePolicy().hasHeightForWidth())
        self.plotQF.setSizePolicy(sizePolicy)
        self.plotQF.setFrameShape(QtGui.QFrame.StyledPanel)
        self.plotQF.setFrameShadow(QtGui.QFrame.Raised)
        self.plotQF.setObjectName(_fromUtf8("plotQF"))
        self.gridLayout_2.addWidget(self.plotQF, 0, 0, 1, 2)
        DM3Viewer.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DM3Viewer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 827, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menu_Export = QtGui.QMenu(self.menuFile)
        self.menu_Export.setObjectName(_fromUtf8("menu_Export"))
        self.menuNavigation = QtGui.QMenu(self.menubar)
        self.menuNavigation.setObjectName(_fromUtf8("menuNavigation"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        DM3Viewer.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DM3Viewer)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        DM3Viewer.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(DM3Viewer)
        self.toolBar.setOrientation(QtCore.Qt.Horizontal)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        DM3Viewer.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_About = QtGui.QAction(DM3Viewer)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/help.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_About.setIcon(icon1)
        self.action_About.setObjectName(_fromUtf8("action_About"))
        self.action_Options = QtGui.QAction(DM3Viewer)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/options.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Options.setIcon(icon2)
        self.action_Options.setObjectName(_fromUtf8("action_Options"))
        self.action_Open_DM3 = QtGui.QAction(DM3Viewer)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/open.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Open_DM3.setIcon(icon3)
        self.action_Open_DM3.setObjectName(_fromUtf8("action_Open_DM3"))
        self.action_Quit_Viewer = QtGui.QAction(DM3Viewer)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/quit.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Quit_Viewer.setIcon(icon4)
        self.action_Quit_Viewer.setObjectName(_fromUtf8("action_Quit_Viewer"))
        self.action_First_Image = QtGui.QAction(DM3Viewer)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/first.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_First_Image.setIcon(icon5)
        self.action_First_Image.setObjectName(_fromUtf8("action_First_Image"))
        self.action_Previous_Image = QtGui.QAction(DM3Viewer)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/previous.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Previous_Image.setIcon(icon6)
        self.action_Previous_Image.setObjectName(_fromUtf8("action_Previous_Image"))
        self.action_Next_Image = QtGui.QAction(DM3Viewer)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/next.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Next_Image.setIcon(icon7)
        self.action_Next_Image.setObjectName(_fromUtf8("action_Next_Image"))
        self.action_Last_Image = QtGui.QAction(DM3Viewer)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/last.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Last_Image.setIcon(icon8)
        self.action_Last_Image.setObjectName(_fromUtf8("action_Last_Image"))
        self.action_Timer = QtGui.QAction(DM3Viewer)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/timer.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Timer.setIcon(icon9)
        self.action_Timer.setObjectName(_fromUtf8("action_Timer"))
        self.action_Export_Data = QtGui.QAction(DM3Viewer)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/save_dat.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Export_Data.setIcon(icon10)
        self.action_Export_Data.setObjectName(_fromUtf8("action_Export_Data"))
        self.action_Export_PNG = QtGui.QAction(DM3Viewer)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/save_png.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Export_PNG.setIcon(icon11)
        self.action_Export_PNG.setObjectName(_fromUtf8("action_Export_PNG"))
        self.action_Export_JPG = QtGui.QAction(DM3Viewer)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/save_jpg.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Export_JPG.setIcon(icon12)
        self.action_Export_JPG.setObjectName(_fromUtf8("action_Export_JPG"))
        self.action_Export_TIF = QtGui.QAction(DM3Viewer)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/save_tif.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Export_TIF.setIcon(icon13)
        self.action_Export_TIF.setObjectName(_fromUtf8("action_Export_TIF"))
        self.action_Export_PDF = QtGui.QAction(DM3Viewer)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/save_pdf.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Export_PDF.setIcon(icon14)
        self.action_Export_PDF.setObjectName(_fromUtf8("action_Export_PDF"))
        self.action_Info = QtGui.QAction(DM3Viewer)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/info.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Info.setIcon(icon15)
        self.action_Info.setObjectName(_fromUtf8("action_Info"))
        self.action_Close_DM3 = QtGui.QAction(DM3Viewer)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/close.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Close_DM3.setIcon(icon16)
        self.action_Close_DM3.setObjectName(_fromUtf8("action_Close_DM3"))
        self.action_Reload_DM3 = QtGui.QAction(DM3Viewer)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/reload.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Reload_DM3.setIcon(icon17)
        self.action_Reload_DM3.setObjectName(_fromUtf8("action_Reload_DM3"))
        self.action_FFT = QtGui.QAction(DM3Viewer)
        self.action_FFT.setCheckable(True)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/fft.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_FFT.setIcon(icon18)
        self.action_FFT.setObjectName(_fromUtf8("action_FFT"))
        self.menu_Export.addAction(self.action_Export_Data)
        self.menu_Export.addAction(self.action_Export_PNG)
        self.menu_Export.addAction(self.action_Export_JPG)
        self.menu_Export.addAction(self.action_Export_TIF)
        self.menu_Export.addAction(self.action_Export_PDF)
        self.menuFile.addAction(self.action_Open_DM3)
        self.menuFile.addAction(self.action_Reload_DM3)
        self.menuFile.addAction(self.action_Close_DM3)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menu_Export.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Quit_Viewer)
        self.menuNavigation.addAction(self.action_First_Image)
        self.menuNavigation.addAction(self.action_Previous_Image)
        self.menuNavigation.addAction(self.action_Next_Image)
        self.menuNavigation.addAction(self.action_Last_Image)
        self.menuTools.addAction(self.action_Info)
        self.menuTools.addAction(self.action_FFT)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.action_Options)
        self.menuTools.addAction(self.action_Timer)
        self.menuHelp.addAction(self.action_About)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuNavigation.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.action_Open_DM3)
        self.toolBar.addAction(self.action_Reload_DM3)
        self.toolBar.addAction(self.action_Close_DM3)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Export_Data)
        self.toolBar.addAction(self.action_Export_PNG)
        self.toolBar.addAction(self.action_Export_JPG)
        self.toolBar.addAction(self.action_Export_TIF)
        self.toolBar.addAction(self.action_Export_PDF)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_First_Image)
        self.toolBar.addAction(self.action_Previous_Image)
        self.toolBar.addAction(self.action_Next_Image)
        self.toolBar.addAction(self.action_Last_Image)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Info)
        self.toolBar.addAction(self.action_FFT)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Options)
        self.toolBar.addAction(self.action_Timer)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_About)

        self.retranslateUi(DM3Viewer)
        QtCore.QMetaObject.connectSlotsByName(DM3Viewer)

    def retranslateUi(self, DM3Viewer):
        DM3Viewer.setWindowTitle(_translate("DM3Viewer", "DM3 Viewer", None))
        self.menuFile.setTitle(_translate("DM3Viewer", "&File", None))
        self.menu_Export.setTitle(_translate("DM3Viewer", "&Export", None))
        self.menuNavigation.setTitle(_translate("DM3Viewer", "&Navigation", None))
        self.menuTools.setTitle(_translate("DM3Viewer", "&Tools", None))
        self.menuHelp.setTitle(_translate("DM3Viewer", "&Help", None))
        self.action_About.setText(_translate("DM3Viewer", "About...", None))
        self.action_About.setToolTip(_translate("DM3Viewer", "About DM3 Viewer", None))
        self.action_About.setStatusTip(_translate("DM3Viewer", "See information about DM3 Viewer", None))
        self.action_About.setShortcut(_translate("DM3Viewer", "F1", None))
        self.action_Options.setText(_translate("DM3Viewer", "&Options...", None))
        self.action_Options.setToolTip(_translate("DM3Viewer", "Edit program options", None))
        self.action_Options.setStatusTip(_translate("DM3Viewer", "Edit configuration options for DM3 Viewer", None))
        self.action_Open_DM3.setText(_translate("DM3Viewer", "&Open DM3 file", None))
        self.action_Open_DM3.setToolTip(_translate("DM3Viewer", "Open DM3 file", None))
        self.action_Open_DM3.setStatusTip(_translate("DM3Viewer", "Select a DM3 file to open", None))
        self.action_Open_DM3.setShortcut(_translate("DM3Viewer", "Ctrl+O", None))
        self.action_Quit_Viewer.setText(_translate("DM3Viewer", "&Quit Viewer", None))
        self.action_Quit_Viewer.setToolTip(_translate("DM3Viewer", "Quit DM3 Viewer", None))
        self.action_Quit_Viewer.setStatusTip(_translate("DM3Viewer", "Quit the application", None))
        self.action_First_Image.setText(_translate("DM3Viewer", "&First image", None))
        self.action_First_Image.setToolTip(_translate("DM3Viewer", "Move to first image", None))
        self.action_First_Image.setStatusTip(_translate("DM3Viewer", "Load the first DM3 image in the current directory", None))
        self.action_First_Image.setShortcut(_translate("DM3Viewer", "Home", None))
        self.action_Previous_Image.setText(_translate("DM3Viewer", "&Previous image", None))
        self.action_Previous_Image.setToolTip(_translate("DM3Viewer", "Move to previous image", None))
        self.action_Previous_Image.setStatusTip(_translate("DM3Viewer", "Load the previous DM3 image in the current directory", None))
        self.action_Previous_Image.setShortcut(_translate("DM3Viewer", "PgUp", None))
        self.action_Next_Image.setText(_translate("DM3Viewer", "&Next image", None))
        self.action_Next_Image.setToolTip(_translate("DM3Viewer", "Move to next image", None))
        self.action_Next_Image.setStatusTip(_translate("DM3Viewer", "Load the next DM3 image in the current directory", None))
        self.action_Next_Image.setShortcut(_translate("DM3Viewer", "PgDown", None))
        self.action_Last_Image.setText(_translate("DM3Viewer", "&Last image", None))
        self.action_Last_Image.setToolTip(_translate("DM3Viewer", "Move to last image", None))
        self.action_Last_Image.setStatusTip(_translate("DM3Viewer", "Load the last DM3 image in the current directory", None))
        self.action_Last_Image.setShortcut(_translate("DM3Viewer", "End", None))
        self.action_Timer.setText(_translate("DM3Viewer", "&Timer", None))
        self.action_Timer.setToolTip(_translate("DM3Viewer", "Timer", None))
        self.action_Timer.setStatusTip(_translate("DM3Viewer", "Iterate automatically over all the DM3 images in the current directory", None))
        self.action_Timer.setShortcut(_translate("DM3Viewer", "Ctrl+T", None))
        self.action_Export_Data.setText(_translate("DM3Viewer", "Export &data...", None))
        self.action_Export_Data.setToolTip(_translate("DM3Viewer", "Export data as text", None))
        self.action_Export_Data.setStatusTip(_translate("DM3Viewer", "Export the data in the current DM3 image as text", None))
        self.action_Export_Data.setShortcut(_translate("DM3Viewer", "Ctrl+D", None))
        self.action_Export_PNG.setText(_translate("DM3Viewer", "Export as &PNG...", None))
        self.action_Export_PNG.setToolTip(_translate("DM3Viewer", "Export image as PNG", None))
        self.action_Export_PNG.setStatusTip(_translate("DM3Viewer", "Export the data in the current DM3 image as PNG", None))
        self.action_Export_PNG.setShortcut(_translate("DM3Viewer", "Ctrl+P", None))
        self.action_Export_JPG.setText(_translate("DM3Viewer", "Export as &JPG...", None))
        self.action_Export_JPG.setToolTip(_translate("DM3Viewer", "Export image as JPG", None))
        self.action_Export_JPG.setStatusTip(_translate("DM3Viewer", "Export the data in the current DM3 image as JPG", None))
        self.action_Export_JPG.setShortcut(_translate("DM3Viewer", "Ctrl+J", None))
        self.action_Export_TIF.setText(_translate("DM3Viewer", "Export as &TIF...", None))
        self.action_Export_TIF.setToolTip(_translate("DM3Viewer", "Export image as TIF", None))
        self.action_Export_TIF.setStatusTip(_translate("DM3Viewer", "Export the data in the current DM3 image as TIF", None))
        self.action_Export_TIF.setShortcut(_translate("DM3Viewer", "Ctrl+T", None))
        self.action_Export_PDF.setText(_translate("DM3Viewer", "Export as PD&F", None))
        self.action_Export_PDF.setToolTip(_translate("DM3Viewer", "Export image as PDF", None))
        self.action_Export_PDF.setStatusTip(_translate("DM3Viewer", "Export the data in the current DM3 image as PDF", None))
        self.action_Export_PDF.setShortcut(_translate("DM3Viewer", "Ctrl+F", None))
        self.action_Info.setText(_translate("DM3Viewer", "&Info...", None))
        self.action_Info.setToolTip(_translate("DM3Viewer", "Image info", None))
        self.action_Info.setStatusTip(_translate("DM3Viewer", "Show the info in the metadata of the current DM3 image", None))
        self.action_Close_DM3.setText(_translate("DM3Viewer", "&Close DM3 file", None))
        self.action_Close_DM3.setStatusTip(_translate("DM3Viewer", "Close the current DM3 file", None))
        self.action_Reload_DM3.setText(_translate("DM3Viewer", "&Reload DM3 file", None))
        self.action_Reload_DM3.setStatusTip(_translate("DM3Viewer", "Reload the current DM3 file", None))
        self.action_FFT.setText(_translate("DM3Viewer", "&FFT", None))
        self.action_FFT.setToolTip(_translate("DM3Viewer", "Fast Fourier Transform", None))
        self.action_FFT.setStatusTip(_translate("DM3Viewer", "Calculate the Fast Fourier Transform of the current DM3 file", None))

import DM3Viewer_rc
