# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'utils/Options.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Options(object):
    def setupUi(self, Options):
        Options.setObjectName(_fromUtf8("Options"))
        Options.setWindowModality(QtCore.Qt.ApplicationModal)
        Options.resize(517, 388)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/options.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Options.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(Options)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.mainTW = QtGui.QTabWidget(Options)
        self.mainTW.setToolTip(_fromUtf8(""))
        self.mainTW.setObjectName(_fromUtf8("mainTW"))
        self.generalTab = QtGui.QWidget()
        self.generalTab.setObjectName(_fromUtf8("generalTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.generalTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblInterval = QtGui.QLabel(self.generalTab)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.lblInterval.setFont(font)
        self.lblInterval.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblInterval.setObjectName(_fromUtf8("lblInterval"))
        self.gridLayout.addWidget(self.lblInterval, 1, 0, 1, 1)
        self.lblZoom = QtGui.QLabel(self.generalTab)
        self.lblZoom.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblZoom.setObjectName(_fromUtf8("lblZoom"))
        self.gridLayout.addWidget(self.lblZoom, 2, 0, 1, 1)
        self.workDirectoryPB = QtGui.QToolButton(self.generalTab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/open.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.workDirectoryPB.setIcon(icon1)
        self.workDirectoryPB.setObjectName(_fromUtf8("workDirectoryPB"))
        self.gridLayout.addWidget(self.workDirectoryPB, 0, 2, 1, 1)
        self.lblPath = QtGui.QLabel(self.generalTab)
        self.lblPath.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPath.setObjectName(_fromUtf8("lblPath"))
        self.gridLayout.addWidget(self.lblPath, 0, 0, 1, 1)
        self.workDirectoryLE = QtGui.QLineEdit(self.generalTab)
        self.workDirectoryLE.setObjectName(_fromUtf8("workDirectoryLE"))
        self.gridLayout.addWidget(self.workDirectoryLE, 0, 1, 1, 1)
        self.timeIntLE = QtGui.QLineEdit(self.generalTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeIntLE.sizePolicy().hasHeightForWidth())
        self.timeIntLE.setSizePolicy(sizePolicy)
        self.timeIntLE.setMinimumSize(QtCore.QSize(150, 0))
        self.timeIntLE.setObjectName(_fromUtf8("timeIntLE"))
        self.gridLayout.addWidget(self.timeIntLE, 1, 1, 1, 2)
        self.zoomHS = QtGui.QSlider(self.generalTab)
        self.zoomHS.setMinimum(-9)
        self.zoomHS.setMaximum(9)
        self.zoomHS.setPageStep(5)
        self.zoomHS.setOrientation(QtCore.Qt.Horizontal)
        self.zoomHS.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.zoomHS.setTickInterval(1)
        self.zoomHS.setObjectName(_fromUtf8("zoomHS"))
        self.gridLayout.addWidget(self.zoomHS, 2, 1, 1, 1)
        self.zoomLbl = QtGui.QLabel(self.generalTab)
        self.zoomLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.zoomLbl.setObjectName(_fromUtf8("zoomLbl"))
        self.gridLayout.addWidget(self.zoomLbl, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.mainTW.addTab(self.generalTab, _fromUtf8(""))
        self.plotTab = QtGui.QWidget()
        self.plotTab.setObjectName(_fromUtf8("plotTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.plotTab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblColorMap = QtGui.QLabel(self.plotTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblColorMap.sizePolicy().hasHeightForWidth())
        self.lblColorMap.setSizePolicy(sizePolicy)
        self.lblColorMap.setMaximumSize(QtCore.QSize(235, 16777215))
        self.lblColorMap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblColorMap.setObjectName(_fromUtf8("lblColorMap"))
        self.gridLayout_2.addWidget(self.lblColorMap, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.colorMapCB = QtGui.QComboBox(self.plotTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorMapCB.sizePolicy().hasHeightForWidth())
        self.colorMapCB.setSizePolicy(sizePolicy)
        self.colorMapCB.setMaximumSize(QtCore.QSize(234, 16777215))
        self.colorMapCB.setObjectName(_fromUtf8("colorMapCB"))
        self.gridLayout_2.addWidget(self.colorMapCB, 0, 1, 1, 1)
        self.lblScalePos = QtGui.QLabel(self.plotTab)
        self.lblScalePos.setObjectName(_fromUtf8("lblScalePos"))
        self.gridLayout_2.addWidget(self.lblScalePos, 0, 2, 1, 1, QtCore.Qt.AlignRight)
        self.scalePosCB = QtGui.QComboBox(self.plotTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scalePosCB.sizePolicy().hasHeightForWidth())
        self.scalePosCB.setSizePolicy(sizePolicy)
        self.scalePosCB.setObjectName(_fromUtf8("scalePosCB"))
        self.scalePosCB.addItem(_fromUtf8(""))
        self.scalePosCB.addItem(_fromUtf8(""))
        self.scalePosCB.addItem(_fromUtf8(""))
        self.scalePosCB.addItem(_fromUtf8(""))
        self.scalePosCB.addItem(_fromUtf8(""))
        self.scalePosCB.addItem(_fromUtf8(""))
        self.scalePosCB.addItem(_fromUtf8(""))
        self.scalePosCB.addItem(_fromUtf8(""))
        self.scalePosCB.addItem(_fromUtf8(""))
        self.scalePosCB.addItem(_fromUtf8(""))
        self.scalePosCB.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.scalePosCB, 0, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.colorMapsQF = QtGui.QFrame(self.plotTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorMapsQF.sizePolicy().hasHeightForWidth())
        self.colorMapsQF.setSizePolicy(sizePolicy)
        self.colorMapsQF.setFrameShape(QtGui.QFrame.StyledPanel)
        self.colorMapsQF.setFrameShadow(QtGui.QFrame.Raised)
        self.colorMapsQF.setObjectName(_fromUtf8("colorMapsQF"))
        self.verticalLayout_3.addWidget(self.colorMapsQF)
        self.mainTW.addTab(self.plotTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.mainTW)
        self.buttonBox = QtGui.QDialogButtonBox(Options)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.Reset)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.lblInterval.setBuddy(self.timeIntLE)
        self.lblPath.setBuddy(self.workDirectoryLE)

        self.retranslateUi(Options)
        self.mainTW.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Options.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Options.reject)
        QtCore.QMetaObject.connectSlotsByName(Options)

    def retranslateUi(self, Options):
        Options.setWindowTitle(_translate("Options", "EDF Viewer - Options", None))
        self.lblInterval.setText(_translate("Options", "Time Interval (s): ", None))
        self.lblZoom.setText(_translate("Options", "Zoom:", None))
        self.workDirectoryPB.setToolTip(_translate("Options", "Select the Base path directory", None))
        self.workDirectoryPB.setText(_translate("Options", "...", None))
        self.lblPath.setToolTip(_translate("Options", "<html><head/><body><p>Base path for input/output.</p></body></html>", None))
        self.lblPath.setText(_translate("Options", "&Working Directory: ", None))
        self.workDirectoryLE.setToolTip(_translate("Options", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">Base path for input/output.</span></p></body></html>", None))
        self.zoomLbl.setText(_translate("Options", "1:1", None))
        self.mainTW.setTabText(self.mainTW.indexOf(self.generalTab), _translate("Options", "&General", None))
        self.lblColorMap.setText(_translate("Options", "Color map: ", None))
        self.colorMapCB.setToolTip(_translate("Options", "Color Map", None))
        self.lblScalePos.setText(_translate("Options", "Scale position:", None))
        self.scalePosCB.setItemText(0, _translate("Options", "No scale", None))
        self.scalePosCB.setItemText(1, _translate("Options", "Upper right", None))
        self.scalePosCB.setItemText(2, _translate("Options", "Upper left", None))
        self.scalePosCB.setItemText(3, _translate("Options", "Lower left", None))
        self.scalePosCB.setItemText(4, _translate("Options", "Lower right", None))
        self.scalePosCB.setItemText(5, _translate("Options", "Right", None))
        self.scalePosCB.setItemText(6, _translate("Options", "Center left", None))
        self.scalePosCB.setItemText(7, _translate("Options", "Center right", None))
        self.scalePosCB.setItemText(8, _translate("Options", "Lower center", None))
        self.scalePosCB.setItemText(9, _translate("Options", "Upper center", None))
        self.scalePosCB.setItemText(10, _translate("Options", "Center", None))
        self.mainTW.setTabText(self.mainTW.indexOf(self.plotTab), _translate("Options", "&Plot", None))

import EDFViewer_rc
